### ISSUE TITLE
Smaller text size than windows font settings. when excutes hta file.

### ISSUE THREAD

**Issue by baramofme** [gnh1201/welsonjs#250]
After applying the registery you mentioned, I ran "app.mshta.exe "C:[somePath]\welsonjs\app.hta"" in Powershell and it works fine. I also executed ".\bootstrap.bat" in Powershell and saw the same thing.

However, I think I need to adjust the zoom setting of internet explorere(?). The text is very small by default. 

I tried changing the style.css file to the following and re-running it, but the text size doesn't change. The reason I separated the html is because rem is a relative unit to the default size, so you need to set the font-size once.

```css
html {
    font-size: 100%; /* or 62.5% (10px ) */
}
body {
    padding: 0;
    margin: 0;
    width: 100%;
	overflow: hidden;
    font-size: 3em;
    font-family: "맑은 고딕", "Malgun Gothic", "Segoe UI", Calibri, Arial, Sans-Serif;
}

```

solution

1. solution was to increase the scale of the expolorer with the `Control`+ `Plus/Minus` keys.

https://github.com/user-attachments/assets/4db14501-ec43-42dc-853c-c9b322848957

2. use css transform 

but popup? size still small. 

```
html {
    font-size: 100%; /* 또는 62.5% (10px 기준) */
    transform: scale(3); /* 2배 확대 */
    transform-origin: top left; /* 확대 기준점 설정 (선택 사항) */
}
body {
    padding: 0;
    margin: 0;
    width: 100%;
	overflow: hidden;
    font-size: 3em;
    font-family: "맑은 고딕", "Malgun Gothic", "Segoe UI", Calibri, Arial, Sans-Serif;
}
```

https://github.com/user-attachments/assets/0e53adfa-6839-4caf-b1b7-5757bece93b3

-----

알려주신 registery 적용 후 파워쉘에서 "app.mshta.exe "C:[somePath]\welsonjs\app.hta"" 실행 잘 됩니다. 파워쉘에서 ".\bootstrap.bat" 도 실행하였고, 동일하게 켜지는 것을 확인하였습니다.

다만, internet explorere(?) 의 확대 축소 설정을 조정할 필요가 있는 것 같습니다. 글씨가 기본적으로 아주 작게 나옵니다. 

혹시나해서 style.css 파일도 아래와 같이 바꿔서 재실행을 시도해 보았으나 글씨 크기가 바뀌지 않습니다.

html 을 따로 분리한 이유는, rem 은 기본 크기에 대한 상대적 단위라서, font-size 를 한번은 설정을 해줘야 하기 때문입니다.

해결책은 컨트롤 플러스 마이너스로 내부 웹엔진(?)의 배율을 조정하거나  CSS trancform 기능을 사용하는 것이었습니다.

다만 CSS transform 을 사용하면, 아래쪽에 뜨는 팝업(?)에는 적용이 안되네요.
